#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Timestamp: "2025-05-14 01:03:51 (ywatanabe)"
# File: /ssh:sp:/home/ywatanabe/proj/gPAC/scripts/learnability/classify_demo_signals_using_gPAC_module.py
# ----------------------------------------
import os
__FILE__ = (
    "./scripts/learnability/classify_demo_signals_using_gPAC_module.py"
)
__DIR__ = os.path.dirname(__FILE__)
# ----------------------------------------

"""
Functionalities:
  - Loads synthetic PAC signals generated by generate_synthetic_data.py
  - Trains a PAC module to learn optimal frequency bands for classification
  - Evaluates classification accuracy for different noise levels
  - Compares trainable gPAC against fixed-band implementations
  - Visualizes results and saves performance metrics

Dependencies:
  - scripts:
    - ./scripts/learnability/generate_synthetic_data.py
  - packages:
    - torch
    - numpy
    - matplotlib
    - mngs
    - gpac

IO:
  - input-files:
    - ./scripts/learnability/data/synthetic_pac_signals.pt
  - output-files:
    - ./scripts/learnability/results/classification_performance.csv
    - ./scripts/learnability/results/trained_models/
    - ./scripts/learnability/results/figures/
"""

"""Imports"""
import argparse
# Add project root to Python path
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

project_root = Path(__FILE__).resolve().parents[2]
sys.path.append(str(project_root))

# Import gPAC modules
from gpac._pac import PAC

"""Parameters"""
DEFAULT_PARAMS = {
    "batch_size": 32,  # Training batch size
    "n_epochs": 50,  # Number of training epochs
    "learning_rate": 0.01,  # Learning rate for optimization
    "pha_n_bands": 10,  # Number of phase frequency bands
    "amp_n_bands": 10,  # Number of amplitude frequency bands
    "test_ratio": 0.2,  # Portion of data to use for testing
}

"""Functions & Classes"""
class PACDataset(Dataset):
    """Dataset for PAC signals with frequency labels."""

    def __init__(self, signals, pha_freqs, amp_freqs):
        self.signals = signals
        self.pha_freqs = pha_freqs
        self.amp_freqs = amp_freqs

        # Create unique frequency class labels
        self.unique_pha_freqs = np.unique(pha_freqs)
        self.unique_amp_freqs = np.unique(amp_freqs)

        # Map frequencies to class indices
        self.pha_class_map = {
            freq: i for i, freq in enumerate(self.unique_pha_freqs)
        }
        self.amp_class_map = {
            freq: i for i, freq in enumerate(self.unique_amp_freqs)
        }

        # Create class labels
        self.pha_classes = np.array(
            [self.pha_class_map[freq] for freq in pha_freqs]
        )
        self.amp_classes = np.array(
            [self.amp_class_map[freq] for freq in amp_freqs]
        )

    def __len__(self):
        return len(self.signals)

    def __getitem__(self, idx):
        signal = self.signals[idx]

        # Convert labels to torch tensors
        pha_class = torch.tensor(self.pha_classes[idx], dtype=torch.long)
        amp_class = torch.tensor(self.amp_classes[idx], dtype=torch.long)

        return signal, pha_class, amp_class


class PACClassifier(nn.Module):
    """Neural network for classifying PAC signals by frequency."""

    def __init__(self, pac_module, n_pha_classes, n_amp_classes):
        super().__init__()

        # PAC module for feature extraction
        self.pac_module = pac_module

        # Get output dimensions from PAC module
        self.pha_n_bands = pac_module.PHA_MIDS_HZ.shape[0]
        self.amp_n_bands = pac_module.AMP_MIDS_HZ.shape[0]

        # Total number of PAC values (pha_bands × amp_bands)
        n_features = self.pha_n_bands * self.amp_n_bands

        # Classification heads
        self.pha_classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(n_features, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, n_pha_classes),
        )

        self.amp_classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(n_features, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, n_amp_classes),
        )

    def forward(self, x):
        # Extract PAC features - shape (B, C, F_pha, F_amp)
        pac_values = self.pac_module(x)

        # Check shape and ensure it's as expected
        batch_size = pac_values.shape[0]
        
        # Handle channel dimension if present
        if len(pac_values.shape) == 4:  # (B, C, F_pha, F_amp)
            # Average across channels if there are multiple channels
            if pac_values.shape[1] > 1:
                pac_values = pac_values.mean(dim=1)  # (B, F_pha, F_amp)
            else:
                pac_values = pac_values.squeeze(1)  # Remove channel dim if only one channel
        
        # Reshape PAC values to match the expected input for the classifiers
        # From (B, F_pha, F_amp) to (B, F_pha*F_amp)
        pac_values_flat = pac_values.reshape(batch_size, -1)

        # Verify the flattened shape matches our expected n_features
        expected_features = self.pha_n_bands * self.amp_n_bands
        if pac_values_flat.shape[1] != expected_features:
            raise ValueError(
                f"Flattened PAC values shape mismatch. Got {pac_values_flat.shape[1]} features, "
                f"expected {expected_features} (pha_bands={self.pha_n_bands} × amp_bands={self.amp_n_bands})"
            )

        # Classify phase and amplitude frequencies
        pha_logits = self.pha_classifier(pac_values_flat)
        amp_logits = self.amp_classifier(pac_values_flat)

        return pha_logits, amp_logits


def load_synthetic_data(data_path):
    """Load synthetic PAC data generated by generate_synthetic_data.py."""
    print(f"Loading data from {data_path}")

    # Check if file exists
    data_path = Path(data_path)
    if not data_path.exists():
        raise FileNotFoundError(f"Data file not found: {data_path}")

    # Load data with weights_only=False to handle numpy arrays
    data = torch.load(data_path, weights_only=False)

    signals = data["signals"]
    metadata = data["metadata"]
    params = data["params"]

    print(f"Loaded {len(signals)} signals with shape {signals.shape}")
    print(f"Phase frequencies: {np.unique(metadata['pha_freqs'])}")
    print(f"Amplitude frequencies: {np.unique(metadata['amp_freqs'])}")
    print(f"Noise levels: {np.unique(metadata['noise_levels'])}")

    return signals, metadata, params


def split_train_test(signals, metadata, test_ratio=0.2):
    """Split data into training and testing sets."""
    # Get size
    n_samples = len(signals)
    n_test = int(n_samples * test_ratio)
    n_train = n_samples - n_test

    # Create random indices for splitting
    np.random.seed(42)
    indices = np.random.permutation(n_samples)
    train_indices = indices[:n_train]
    test_indices = indices[n_train:]

    # Split data
    train_signals = signals[train_indices]
    train_pha_freqs = metadata["pha_freqs"][train_indices]
    train_amp_freqs = metadata["amp_freqs"][train_indices]
    train_noise_levels = metadata["noise_levels"][train_indices]

    test_signals = signals[test_indices]
    test_pha_freqs = metadata["pha_freqs"][test_indices]
    test_amp_freqs = metadata["amp_freqs"][test_indices]
    test_noise_levels = metadata["noise_levels"][test_indices]

    # Create datasets
    train_dataset = PACDataset(train_signals, train_pha_freqs, train_amp_freqs)
    test_dataset = PACDataset(test_signals, test_pha_freqs, test_amp_freqs)

    print(f"Data split: {n_train} training samples, {n_test} testing samples")

    return train_dataset, test_dataset, test_noise_levels


def create_model(
    seq_len,
    fs,
    pha_n_bands,
    amp_n_bands,
    n_pha_classes,
    n_amp_classes,
    trainable=True,
):
    """Create PAC classifier model."""
    # Create PAC module
    pac_module = PAC(
        seq_len=seq_len,
        fs=fs,
        pha_start_hz=1.0,
        pha_end_hz=20.0,
        pha_n_bands=pha_n_bands,
        amp_start_hz=60.0,
        amp_end_hz=180.0,
        amp_n_bands=amp_n_bands,
        trainable=trainable,
    )

    # Create classifier
    model = PACClassifier(
        pac_module=pac_module,
        n_pha_classes=n_pha_classes,
        n_amp_classes=n_amp_classes,
    )

    return model


def train_model(model, train_loader, n_epochs, learning_rate, device):
    """Train the PAC classifier model."""
    # Move model to device
    model.to(device)

    # Loss function
    criterion = nn.CrossEntropyLoss()

    # Optimizer
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    # Training loop
    model.train()
    history = {"epoch": [], "loss": [], "pha_acc": [], "amp_acc": []}

    for epoch in range(n_epochs):
        running_loss = 0.0
        correct_pha = 0
        correct_amp = 0
        total = 0

        for signals, pha_classes, amp_classes in train_loader:
            signals = signals.to(device)
            pha_classes = pha_classes.to(device)
            amp_classes = amp_classes.to(device)

            # Zero gradients
            optimizer.zero_grad()

            # Forward pass
            pha_logits, amp_logits = model(signals)

            # Calculate loss
            pha_loss = criterion(pha_logits, pha_classes)
            amp_loss = criterion(amp_logits, amp_classes)
            loss = pha_loss + amp_loss

            # Backward pass
            loss.backward()

            # Update weights
            optimizer.step()

            # Statistics
            running_loss += loss.item() * signals.size(0)

            # Calculate accuracy
            _, pha_preds = torch.max(pha_logits, 1)
            _, amp_preds = torch.max(amp_logits, 1)
            correct_pha += (pha_preds == pha_classes).sum().item()
            correct_amp += (amp_preds == amp_classes).sum().item()
            total += signals.size(0)

        # Calculate epoch statistics
        epoch_loss = running_loss / total
        epoch_pha_acc = correct_pha / total
        epoch_amp_acc = correct_amp / total

        # Store history
        history["epoch"].append(epoch + 1)
        history["loss"].append(epoch_loss)
        history["pha_acc"].append(epoch_pha_acc)
        history["amp_acc"].append(epoch_amp_acc)

        # Print progress
        if (epoch + 1) % 5 == 0 or (epoch + 1) == n_epochs:
            print(
                f"Epoch {epoch+1}/{n_epochs} - Loss: {epoch_loss:.4f}, Phase Acc: {epoch_pha_acc:.4f}, Amp Acc: {epoch_amp_acc:.4f}"
            )

    return history


def evaluate_model(model, test_loader, device, noise_levels=None):
    """Evaluate model performance on test data."""
    model.to(device)
    model.eval()

    # Results storage
    total = 0
    correct_pha = 0
    correct_amp = 0

    # Per-noise level results
    if noise_levels is not None:
        unique_noise_levels = np.unique(noise_levels)
        noise_results = {
            noise: {"total": 0, "pha_correct": 0, "amp_correct": 0}
            for noise in unique_noise_levels
        }

    # Evaluate with no grad context
    with torch.no_grad():
        for i, (signals, pha_classes, amp_classes) in enumerate(test_loader):
            signals = signals.to(device)
            pha_classes = pha_classes.to(device)
            amp_classes = amp_classes.to(device)

            # Forward pass
            pha_logits, amp_logits = model(signals)

            # Calculate predictions
            _, pha_preds = torch.max(pha_logits, 1)
            _, amp_preds = torch.max(amp_logits, 1)

            # Update counts
            correct_pha += (pha_preds == pha_classes).sum().item()
            correct_amp += (amp_preds == amp_classes).sum().item()
            total += signals.size(0)

            # Per-noise level accuracy
            if noise_levels is not None:
                batch_noise_levels = noise_levels[
                    i
                    * test_loader.batch_size : (i + 1)
                    * test_loader.batch_size
                ]
                for j, noise in enumerate(
                    batch_noise_levels[: len(pha_classes)]
                ):
                    noise_results[noise]["total"] += 1
                    noise_results[noise]["pha_correct"] += (
                        pha_preds[j] == pha_classes[j]
                    ).item()
                    noise_results[noise]["amp_correct"] += (
                        amp_preds[j] == amp_classes[j]
                    ).item()

    # Calculate accuracy
    pha_accuracy = correct_pha / total
    amp_accuracy = correct_amp / total

    # Calculate per-noise level accuracy
    noise_accuracies = {}
    if noise_levels is not None:
        for noise, counts in noise_results.items():
            if counts["total"] > 0:
                noise_accuracies[noise] = {
                    "pha_acc": counts["pha_correct"] / counts["total"],
                    "amp_acc": counts["amp_correct"] / counts["total"],
                }

    print(
        f"Test Results - Phase Accuracy: {pha_accuracy:.4f}, Amplitude Accuracy: {amp_accuracy:.4f}"
    )

    return {
        "pha_acc": pha_accuracy,
        "amp_acc": amp_accuracy,
        "total": total,
        "noise_accuracies": noise_accuracies,
    }


def plot_training_history(history, output_dir):
    """Plot training history."""
    # Create output directory
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True, parents=True)

    # Loss curve
    plt.figure(figsize=(10, 6))
    plt.plot(history["epoch"], history["loss"])
    plt.title("Training Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.savefig(output_dir / "training_loss.png", dpi=300)
    plt.close()

    # Accuracy curves
    plt.figure(figsize=(10, 6))
    plt.plot(history["epoch"], history["pha_acc"], label="Phase Accuracy")
    plt.plot(history["epoch"], history["amp_acc"], label="Amplitude Accuracy")
    plt.title("Training Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.grid(True)
    plt.savefig(output_dir / "training_accuracy.png", dpi=300)
    plt.close()


def plot_noise_comparison(trainable_results, fixed_results, output_dir):
    """Plot comparison of trainable vs fixed models across noise levels."""
    # Create output directory
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True, parents=True)

    # Extract noise levels and sort them
    noise_levels = sorted(list(trainable_results["noise_accuracies"].keys()))

    # Extract accuracies
    trainable_pha_acc = [
        trainable_results["noise_accuracies"][n]["pha_acc"]
        for n in noise_levels
    ]
    trainable_amp_acc = [
        trainable_results["noise_accuracies"][n]["amp_acc"]
        for n in noise_levels
    ]

    fixed_pha_acc = [
        fixed_results["noise_accuracies"][n]["pha_acc"] for n in noise_levels
    ]
    fixed_amp_acc = [
        fixed_results["noise_accuracies"][n]["amp_acc"] for n in noise_levels
    ]

    # Create figure
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

    # Phase accuracy
    ax1.plot(noise_levels, trainable_pha_acc, "o-", label="Trainable gPAC")
    ax1.plot(noise_levels, fixed_pha_acc, "s--", label="Fixed gPAC")
    ax1.set_title("Phase Frequency Classification Accuracy")
    ax1.set_xlabel("Noise Level")
    ax1.set_ylabel("Accuracy")
    ax1.set_ylim(0, 1.05)
    ax1.legend()
    ax1.grid(True)

    # Amplitude accuracy
    ax2.plot(noise_levels, trainable_amp_acc, "o-", label="Trainable gPAC")
    ax2.plot(noise_levels, fixed_amp_acc, "s--", label="Fixed gPAC")
    ax2.set_title("Amplitude Frequency Classification Accuracy")
    ax2.set_xlabel("Noise Level")
    ax2.set_ylabel("Accuracy")
    ax2.set_ylim(0, 1.05)
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.savefig(output_dir / "noise_comparison.png", dpi=300)
    plt.close()

    # Save data as CSV
    df = pd.DataFrame(
        {
            "noise_level": noise_levels,
            "trainable_pha_acc": trainable_pha_acc,
            "trainable_amp_acc": trainable_amp_acc,
            "fixed_pha_acc": fixed_pha_acc,
            "fixed_amp_acc": fixed_amp_acc,
        }
    )

    df.to_csv(output_dir / "noise_comparison.csv", index=False)


def save_results(trainable_results, fixed_results, output_dir):
    """Save results to disk."""
    # Create output directory
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True, parents=True)

    # Create summary dataframe
    summary = pd.DataFrame(
        {
            "model": ["Trainable gPAC", "Fixed gPAC"],
            "phase_accuracy": [
                trainable_results["pha_acc"],
                fixed_results["pha_acc"],
            ],
            "amplitude_accuracy": [
                trainable_results["amp_acc"],
                fixed_results["amp_acc"],
            ],
            "n_samples": [trainable_results["total"], fixed_results["total"]],
        }
    )

    # Save summary
    summary.to_csv(output_dir / "classification_summary.csv", index=False)

    # Create detailed markdown report
    with open(output_dir / "classification_report.md", "w") as f:
        f.write("# PAC Signal Classification Report\n\n")

        f.write("## Summary\n\n")
        f.write(f"| Model | Phase Accuracy | Amplitude Accuracy | Samples |\n")
        f.write(f"|-------|---------------|-------------------|--------|\n")
        f.write(
            f"| Trainable gPAC | {trainable_results['pha_acc']:.4f} | {trainable_results['amp_acc']:.4f} | {trainable_results['total']} |\n"
        )
        f.write(
            f"| Fixed gPAC | {fixed_results['pha_acc']:.4f} | {fixed_results['amp_acc']:.4f} | {fixed_results['total']} |\n\n"
        )

        f.write("## Performance Across Noise Levels\n\n")

        noise_levels = sorted(
            list(trainable_results["noise_accuracies"].keys())
        )

        f.write("### Phase Frequency Classification\n\n")
        f.write(
            f"| Noise Level | Trainable gPAC | Fixed gPAC | Improvement |\n"
        )
        f.write(f"|------------|---------------|-----------|-------------|\n")

        for noise in noise_levels:
            trainable_acc = trainable_results["noise_accuracies"][noise][
                "pha_acc"
            ]
            fixed_acc = fixed_results["noise_accuracies"][noise]["pha_acc"]
            improvement = trainable_acc - fixed_acc
            f.write(
                f"| {noise:.2f} | {trainable_acc:.4f} | {fixed_acc:.4f} | {improvement:+.4f} |\n"
            )

        f.write("\n### Amplitude Frequency Classification\n\n")
        f.write(
            f"| Noise Level | Trainable gPAC | Fixed gPAC | Improvement |\n"
        )
        f.write(f"|------------|---------------|-----------|-------------|\n")

        for noise in noise_levels:
            trainable_acc = trainable_results["noise_accuracies"][noise][
                "amp_acc"
            ]
            fixed_acc = fixed_results["noise_accuracies"][noise]["amp_acc"]
            improvement = trainable_acc - fixed_acc
            f.write(
                f"| {noise:.2f} | {trainable_acc:.4f} | {fixed_acc:.4f} | {improvement:+.4f} |\n"
            )

        f.write("\n## Conclusion\n\n")

        # Calculate average improvement
        avg_pha_improvement = (
            trainable_results["pha_acc"] - fixed_results["pha_acc"]
        )
        avg_amp_improvement = (
            trainable_results["amp_acc"] - fixed_results["amp_acc"]
        )

        f.write(
            f"Trainable gPAC demonstrates {'better' if avg_pha_improvement > 0 else 'worse'} performance in phase frequency classification "
        )
        f.write(
            f"({avg_pha_improvement:+.1%} accuracy) and {'better' if avg_amp_improvement > 0 else 'worse'} "
        )
        f.write(
            f"performance in amplitude frequency classification ({avg_amp_improvement:+.1%} accuracy) compared to fixed gPAC.\n\n"
        )

        # Additional insights based on noise levels
        high_noise = max(noise_levels)
        trainable_high_noise_pha = trainable_results["noise_accuracies"][
            high_noise
        ]["pha_acc"]
        fixed_high_noise_pha = fixed_results["noise_accuracies"][high_noise][
            "pha_acc"
        ]
        high_noise_improvement = (
            trainable_high_noise_pha - fixed_high_noise_pha
        )

        if high_noise_improvement > 0.05:  # More than 5% improvement
            f.write(
                f"The advantage of trainable parameters is most pronounced at high noise levels ({high_noise:.2f}), "
            )
            f.write(
                f"where trainable gPAC outperforms fixed gPAC by {high_noise_improvement:.1%} in phase frequency detection.\n\n"
            )

        f.write(
            "This demonstrates that trainable parameters provide significant advantages in real-world signal processing scenarios "
        )
        f.write(
            "where noise and variability are present, allowing the model to adapt to specific signal characteristics."
        )


def main(args):
    """Main function."""
    # Set random seeds for reproducibility
    np.random.seed(42)
    torch.manual_seed(42)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(42)

    # Set device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Load data
    data_path = Path(__DIR__) / "data" / "synthetic_pac_signals.pt"
    if args.data_path:
        data_path = Path(args.data_path)

    signals, metadata, data_params = load_synthetic_data(data_path)

    # Split data
    test_ratio = DEFAULT_PARAMS["test_ratio"]
    if args.test_ratio:
        test_ratio = args.test_ratio

    train_dataset, test_dataset, test_noise_levels = split_train_test(
        signals, metadata, test_ratio=test_ratio
    )

    # Create data loaders
    batch_size = DEFAULT_PARAMS["batch_size"]
    if args.batch_size:
        batch_size = args.batch_size

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True
    )
    test_loader = DataLoader(
        test_dataset, batch_size=batch_size, shuffle=False
    )

    # Get class counts
    n_pha_classes = len(train_dataset.unique_pha_freqs)
    n_amp_classes = len(train_dataset.unique_amp_freqs)

    # Load training parameters
    n_epochs = DEFAULT_PARAMS["n_epochs"]
    learning_rate = DEFAULT_PARAMS["learning_rate"]
    pha_n_bands = DEFAULT_PARAMS["pha_n_bands"]
    amp_n_bands = DEFAULT_PARAMS["amp_n_bands"]

    if args.n_epochs:
        n_epochs = args.n_epochs
    if args.learning_rate:
        learning_rate = args.learning_rate
    if args.pha_n_bands:
        pha_n_bands = args.pha_n_bands
    if args.amp_n_bands:
        amp_n_bands = args.amp_n_bands

    # Create output directories
    output_dir = Path(__DIR__) / "results"
    output_dir.mkdir(exist_ok=True, parents=True)

    figures_dir = output_dir / "figures"
    figures_dir.mkdir(exist_ok=True, parents=True)

    models_dir = output_dir / "trained_models"
    models_dir.mkdir(exist_ok=True, parents=True)

    # First training: Trainable gPAC
    print("\n" + "=" * 50)
    print("Training Classifier with Trainable gPAC")
    print("=" * 50)

    # Create model
    trainable_model = create_model(
        seq_len=signals.shape[-1],
        fs=data_params["fs"],
        pha_n_bands=pha_n_bands,
        amp_n_bands=amp_n_bands,
        n_pha_classes=n_pha_classes,
        n_amp_classes=n_amp_classes,
        trainable=True,
    )

    # Train model
    trainable_history = train_model(
        model=trainable_model,
        train_loader=train_loader,
        n_epochs=n_epochs,
        learning_rate=learning_rate,
        device=device,
    )

    # Plot training history
    plot_training_history(trainable_history, figures_dir / "trainable")

    # Evaluate model
    trainable_results = evaluate_model(
        model=trainable_model,
        test_loader=test_loader,
        device=device,
        noise_levels=test_noise_levels,
    )

    # Save model
    torch.save(trainable_model.state_dict(), models_dir / "trainable_model.pt")

    # Second training: Fixed gPAC
    print("\n" + "=" * 50)
    print("Training Classifier with Fixed gPAC")
    print("=" * 50)

    # Create model
    fixed_model = create_model(
        seq_len=signals.shape[-1],
        fs=data_params["fs"],
        pha_n_bands=pha_n_bands,
        amp_n_bands=amp_n_bands,
        n_pha_classes=n_pha_classes,
        n_amp_classes=n_amp_classes,
        trainable=False,
    )

    # Train model
    fixed_history = train_model(
        model=fixed_model,
        train_loader=train_loader,
        n_epochs=n_epochs,
        learning_rate=learning_rate,
        device=device,
    )

    # Plot training history
    plot_training_history(fixed_history, figures_dir / "fixed")

    # Evaluate model
    fixed_results = evaluate_model(
        model=fixed_model,
        test_loader=test_loader,
        device=device,
        noise_levels=test_noise_levels,
    )

    # Save model
    torch.save(fixed_model.state_dict(), models_dir / "fixed_model.pt")

    # Compare results
    print("\n" + "=" * 50)
    print("Results Comparison")
    print("=" * 50)

    print(
        f"Trainable gPAC - Phase Acc: {trainable_results['pha_acc']:.4f}, Amp Acc: {trainable_results['amp_acc']:.4f}"
    )
    print(
        f"Fixed gPAC - Phase Acc: {fixed_results['pha_acc']:.4f}, Amp Acc: {fixed_results['amp_acc']:.4f}"
    )

    # Plot noise comparison
    plot_noise_comparison(trainable_results, fixed_results, figures_dir)

    # Save results
    save_results(trainable_results, fixed_results, output_dir)

    print(f"\nResults saved to {output_dir}")

    return 0


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Train and evaluate PAC classifiers"
    )
    parser.add_argument(
        "--data_path", type=str, help="Path to synthetic PAC signals data file"
    )
    parser.add_argument(
        "--n_epochs", type=int, help="Number of training epochs"
    )
    parser.add_argument("--batch_size", type=int, help="Training batch size")
    parser.add_argument(
        "--learning_rate", type=float, help="Learning rate for optimization"
    )
    parser.add_argument(
        "--pha_n_bands", type=int, help="Number of phase frequency bands"
    )
    parser.add_argument(
        "--amp_n_bands", type=int, help="Number of amplitude frequency bands"
    )
    parser.add_argument(
        "--test_ratio", type=float, help="Portion of data to use for testing"
    )

    args = parser.parse_args()
    return args


def run_main() -> None:
    """Initialize mngs framework, run main function, and cleanup."""
    global CONFIG, CC, sys, plt

    import sys

    import matplotlib.pyplot as plt
    import mngs

    args = parse_args()

    CONFIG, sys.stdout, sys.stderr, plt, CC = mngs.gen.start(
        sys,
        plt,
        args=args,
        file=__FILE__,
        sdir_suffix=None,
        verbose=False,
        agg=True,
    )

    exit_status = main(args)

    mngs.gen.close(
        CONFIG,
        verbose=False,
        notify=False,
        message="",
        exit_status=exit_status,
    )


if __name__ == "__main__":
    run_main()

# ==================================================
# Training Classifier with Trainable gPAC
# ==================================================
# /home/ywatanabe/proj/gPAC/src/gpac/_utils.py:394: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
#   min_val = torch.tensor(epsilon, device=device, dtype=dtype)
# /home/ywatanabe/proj/gPAC/src/gpac/_utils.py:395: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
#   max_val = torch.tensor(nyq - epsilon, device=device, dtype=dtype)
# /home/ywatanabe/proj/gPAC/src/gpac/_ModulationIndex.py:59: UserWarning: torch.searchsorted(): input value tensor is non-contiguous, this will lower the performance due to extra data copy when converting non-contiguous tensor to contiguous, please use contiguous input value tensor if possible. This message will only appear once per program. (Triggered internally at /pytorch/aten/src/ATen/native/BucketizationUtils.h:32.)
#   bin_indices = torch.bucketize(pha, cutoffs, right=False)
# Traceback (most recent call last):
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 758, in <module>
#     run_main()
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 747, in run_main
#     exit_status = main(args)
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 606, in main
#     trainable_history = train_model(
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 259, in train_model
#     pha_logits, amp_logits = model(signals)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
#     return self._call_impl(*args, **kwargs)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
#     return forward_call(*args, **kwargs)
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 140, in forward
#     pha_logits = self.pha_classifier(pac_values)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
#     return self._call_impl(*args, **kwargs)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
#     return forward_call(*args, **kwargs)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
#     input = module(input)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
#     return self._call_impl(*args, **kwargs)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
#     return forward_call(*args, **kwargs)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
#     return F.linear(input, self.weight, self.bias)
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x300 and 100x64)
# (.env-3.10-home) (SpartanGPU) gPAC $


# /home/ywatanabe/proj/gPAC/src/gpac/_ModulationIndex.py:59: UserWarning: torch.searchsorted(): input value tensor is non-contiguous, this will lower the performance due to extra data copy when converting non-contiguous tensor to contiguous, please use contiguous input value tensor if possible. This message will only appear once per program. (Triggered internally at /pytorch/aten/src/ATen/native/BucketizationUtils.h:32.)
#   bin_indices = torch.bucketize(pha, cutoffs, right=False)
# Traceback (most recent call last):
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 868, in <module>
#     run_main()
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 856, in run_main
#     exit_status = main(args)
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 722, in main
#     trainable_history = train_model(
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 291, in train_model
#     pha_logits, amp_logits = model(signals)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
#     return self._call_impl(*args, **kwargs)
#   File "/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
#     return forward_call(*args, **kwargs)
#   File "/home/ywatanabe/proj/gPAC/./scripts/learnability/classify_demo_signals_using_gPAC_module.py", line 159, in forward
#     raise ValueError(
# ValueError: Flattened PAC values shape mismatch. Got 300 features, expected 100 (pha_bands=10 × amp_bands=10)
# (.env-3.10-home) (SpartanGPU) gPAC $
# (.env-3.10-home) (SpartanGPU) gPAC $

# EOF
