#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate an org-mode test report from pytest results by directly using pytest plugin hooks.
"""

import sys
import os
import re
import time
import subprocess
from datetime import datetime

# Add project root to Python path to fix imports
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

import pytest
from _pytest.config import Config
from _pytest.terminal import TerminalReporter
from _pytest.runner import TestReport

# Global variables to store test results
test_results = {
    'passed': [],
    'failed': [],
    'skipped': [],
    'execution_time': 0.0
}

# Custom pytest plugin to collect results
class ResultCollector:
    def __init__(self):
        self.reports = []
        self.execution_start_time = time.time()
        
    def pytest_runtest_logreport(self, report):
        """Called for each test report"""
        if report.when == 'call' or (report.when == 'setup' and report.skipped):
            # Get test info
            test_info = {
                'file': report.fspath,
                'test': report.nodeid.split('::')[-1] if '::' in report.nodeid else report.nodeid,
                'status': report.outcome.upper(),
                'details': '',
                'nodeid': report.nodeid
            }
            
            # For classes, include the class name
            parts = report.nodeid.split('::')
            if len(parts) > 2:
                class_name = parts[-2]
                test_name = parts[-1]
                test_info['test'] = f"{class_name}::{test_name}"
            
            # Add test to appropriate list
            if report.passed:
                test_results['passed'].append(test_info)
            elif report.failed:
                # Get failure details
                if hasattr(report, 'longrepr'):
                    test_info['details'] = str(report.longrepr)
                test_results['failed'].append(test_info)
            elif report.skipped:
                test_results['skipped'].append(test_info)
                
            self.reports.append(test_info)
    
    def pytest_sessionfinish(self, session):
        """Called after whole test run finished"""
        test_results['execution_time'] = time.time() - self.execution_start_time
        
def run_pytest_and_collect_results():
    """Run pytest and collect results using our custom plugin"""
    # Register our plugin with pytest
    collector = ResultCollector()
    
    # Add command line options to ensure proper Python path
    pytest.main(['tests/', '-v', '--import-mode=importlib'], plugins=[collector])
    
    # Prepare final results
    return {
        'passed': test_results['passed'],
        'failed': test_results['failed'],
        'skipped': test_results['skipped'],
        'total': len(test_results['passed']) + len(test_results['failed']) + len(test_results['skipped']),
        'execution_time': test_results['execution_time'],
        'by_file': group_tests_by_file(test_results)
    }

def group_tests_by_file(results):
    """Group tests by file for better organization in report"""
    tests_by_file = {}
    
    # Group passed tests
    for test in results['passed']:
        file_path = str(test['file'])
        if file_path not in tests_by_file:
            tests_by_file[file_path] = []
        tests_by_file[file_path].append(test)
    
    # Group failed tests
    for test in results['failed']:
        file_path = str(test['file'])
        if file_path not in tests_by_file:
            tests_by_file[file_path] = []
        tests_by_file[file_path].append(test)
    
    # Group skipped tests
    for test in results['skipped']:
        file_path = str(test['file'])
        if file_path not in tests_by_file:
            tests_by_file[file_path] = []
        tests_by_file[file_path].append(test)
    
    return tests_by_file

def generate_org_report(test_info):
    """Generate an org-mode formatted test report"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = test_info['total']
    passed = len(test_info['passed'])
    failed = len(test_info['failed'])
    skipped = len(test_info['skipped'])
    
    success_rate = (passed / total * 100) if total > 0 else 0
    
    # Prepare the report
    report = []
    report.append(f"#+TITLE: gPAC Test Report")
    report.append(f"#+AUTHOR: Generated by generate_org_test_report.py")
    report.append(f"#+DATE: {now}")
    report.append("")
    report.append("* Test Results Summary")
    report.append(f"- Passed: {passed}")
    report.append(f"- Failed: {failed}")
    report.append(f"- Skipped: {skipped}")
    report.append(f"- Total: {total}")
    report.append(f"- Total Time: {test_info['execution_time']} seconds")
    report.append(f"- Success Rate: {success_rate:.1f}%")
    report.append("")
    
    # Add passed tests
    if test_info['passed']:
        report.append("* Passed Tests ({})".format(passed))
        report.append("")
        
        passed_by_file = {}
        for test in test_info['passed']:
            file = test['file']
            if file not in passed_by_file:
                passed_by_file[file] = []
            passed_by_file[file].append(test)
        
        for file, tests in sorted(passed_by_file.items()):
            report.append(f"** {file} ({len(tests)} tests)")
            for test in tests:
                test_name = test['test']
                report.append(f"- [[file:{file}::{test_name}][{test_name}]]")
            report.append("")
    
    # Add failed tests
    if test_info['failed']:
        report.append("* Failed Tests ({})".format(failed))
        report.append("")
        
        failed_by_file = {}
        for test in test_info['failed']:
            file = test['file']
            if file not in failed_by_file:
                failed_by_file[file] = []
            failed_by_file[file].append(test)
        
        for file, tests in sorted(failed_by_file.items()):
            report.append(f"** {file} ({len(tests)} tests)")
            for test in tests:
                test_name = test['test']
                report.append(f"- [[file:{file}::{test_name}][{test_name}]]")
                if test['details']:
                    report.append("  + Error details:")
                    # Indent the details for org-mode format
                    for line in test['details'].split('\n'):
                        report.append(f"    {line}")
            report.append("")
    
    # Add skipped tests
    if test_info['skipped']:
        report.append("* Skipped Tests ({})".format(skipped))
        report.append("")
        
        skipped_by_file = {}
        for test in test_info['skipped']:
            file = test['file']
            if file not in skipped_by_file:
                skipped_by_file[file] = []
            skipped_by_file[file].append(test)
        
        for file, tests in sorted(skipped_by_file.items()):
            report.append(f"** {file} ({len(tests)} tests)")
            for test in tests:
                test_name = test['test']
                report.append(f"- [[file:{file}::{test_name}][{test_name}]]")
            report.append("")
    
    return '\n'.join(report)

def main():
    """Main function to run tests and generate report"""
    # Collect test results using pytest plugin approach
    test_info = run_pytest_and_collect_results()
    
    # Generate org-mode report
    org_report = generate_org_report(test_info)
    
    # Write report to file
    report_path = os.path.join(os.getcwd(), "test_report.org")
    with open(report_path, 'w') as f:
        f.write(org_report)
        
    print(f"Test report generated at {report_path}")
    return 0 if not test_info['failed'] else 1

if __name__ == "__main__":
    sys.exit(main())